name = "CFKI Client"
author = "DeeKahy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e7d03f5e43e95a5f1d70852243a55f5751e4ebc2a0645f6a7c1ad9e1ac00e04"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
