name = "CFKI Client"
author = "DeeKahy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fec025bc914c96b776ec2a41a3ecb7f905c5b0f96faa75f9e7ae7be63f3c3f8a"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
