name = "CFKI Client"
author = "DeeKahy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8c5fbbdf1e7c3315d5bbc6deabe17067c6cd0c6f730657e0b1c8f5a4bd04886"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
