name = "CFKI Server"
author = "DeeKahy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d3fd2f35e069991c36c6b228259cae7e032b8c63a2b9d4245fd857e65ce527a"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
