name = "CFKI Server"
author = "DeeKahy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c0b35f9161eee48f1d859c5990365cacb53f60d78a13b3529a60d04116552e5"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
