name = "CFKI Server"
author = "DeeKahy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4002ce6f25f5787c3f8fd6fbf5773512c60d06c7e1f0fd787810617a7d871d89"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
