name = "Technical Vanilla"
author = "DeeKahy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "722e77f521e737eeab291854971de1a54698a6e21fbc94cb8fc48962f452ddc5"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
