name = "Technical Vanilla"
author = "DeeKahy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e364d8cce7d34810d2bb5adbff14a6a2d2d8249501516e0776b026eabd46b35e"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
