name = "Technical Vanilla"
author = "DeeKahy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d92a2cefd0506cb35c88a37d0c73e86bfc0700d8d9fd2f07b4b59d26f6793767"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
